version: '3'

services:
  mysql:
    image: mysql:8.0.1
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Zolotoy585
    volumes:
      - ./data:/var/lib/mysql/
    networks:
      - net1

  phpadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin
    restart: always
    environment:
      PMA_HOST: mysql
    ports:
      - "11080:80"
    depends_on:
      - mysql
    networks:
      - net1

  myphp:
    image: php:7.3-fpm
    restart: always
    volumes:
      - /var/www/devops/:/var/www/html/
    networks:
      - net1

  nginx:
    image: nginx:1.17.6-alpine
    container_name: nginx
    restart: always
    ports:
      - "11090:80"
    depends_on:
      - mysql
      - myphp
    volumes:
      - ./nginx/phpadmin.conf:/etc/nginx/conf.d/default.conf
      - /var/www/devops/:/var/www/html/
    networks:
      - net1

networks:
  net1:
   driver: bridge


