version: '3'

services:
  mysql:
    image: mysql:8.0.1
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Zolotoy585
    volumes:
      - ./data:/var/lib/mysql/
      - /var/www/devops/:/var/www/devops/
    networks:
      - net1

  phpadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin
    restart: always
    ports:
      - "11080:80"
    depends_on:
      - mysql
    volumes:
      - /var/www/devops/:/var/www/devops/
    networks:
      - net1

  nginx:
    image: nginx:1.17.6-alpine
    container_name: nginx
    restart: always
    ports:
      - "11090:80"
    depends_on:
      - mysql
      - phpadmin
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /var/www/devops/:/var/www/devops/
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - net1

networks:
  net1:
   driver: bridge


